openapi: 3.0.0
 
info:
  version: 1.0.0
  title: Library Service
  description: The library service

servers: 
  # Added by API Auto Mocking Plugin
  #- description: SwaggerHub API Auto Mocking
  #  url: https://virtserver.swaggerhub.com/ALIDRISSIAKRAM/api-rest-formation-book/1.0.0
  - description: dev 
    url: 'http://localhost:8080'
    

tags:
  - name: "Library"
  - name : "Users"
 
 
paths:
 
  /books:
    get:
      summary: This is summary
      tags:
        - "Library"
      description: This is a description
      operationId: getAllBooksInLibrary
      responses:
        "200":
          description: This means its ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        #Aajouter
        "400":
          description: Bad resquest
        "401":
          description: Unauthorized
    post:
      summary: book creation
      tags: 
        - "Library"
      operationId: idBookCreation
      responses:
        "201":
          description: CREATED
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
components:
 
  schemas:
 
    Book:
      description: This is the book model
      type: object
      required: 
        - name
      properties:
        name:
          description: The name of book
          type: string
        bookAuthor:
          description: name of author
          type: string
        #Aajouter
        price:
          description: price of product
          type: integer